### ISSUE TITLE
"measured" optode positions are exactly the same for all subjects and probably represent template positions

### ISSUE THREAD

**Issue by robertoostenveld** [rob-luke/BIDS-NIRS-Tapping#2]
When comparing https://github.com/rob-luke/BIDS-NIRS-Tapping/blob/master/sub-01/nirs/sub-01_optodes.tsv to https://github.com/rob-luke/BIDS-NIRS-Tapping/blob/master/sub-02/nirs/sub-02_optodes.tsv I noticed that the measured opted positions are exactly the same. This suggests that the positions were not measured on the actual subjects, but possibly on a template subject or on a styrofoam head. 

If that is the case, `template_x`, `template_y`, and `template_z` should be used and the measured positions should be specified as `n/a` according to https://github.com/bids-standard/bids-specification/blob/cbf34ac830d3eb2b917b410747169b41bd05f8e1/src/04-modality-specific-files/10-functional-near-infrared-spectroscopy.md.

**Comment by rob-luke** [comment]
You are 100% correct. I will make this change ASAP
